// Version file for Letter Loom
// Automatically updated by CI/CD. Do not edit manually.
// Local override: app/src/core/version.local.js (gitignored) — regenerated by the post-commit hook.
// version.local.js is only updated on commit, so it may be stale if you modify files without committing.
// This only affects the version shown in the help screen; the SW in local dev should be bypassed via DevTools.
import { IS_LOCAL } from '../lib/env.js'

const VERSION_PREFIX = "1.0" // read by CI and post-commit hook via grep

let _version = "v1.0.854"

if (IS_LOCAL) {
  try {
    const m = await import('./version.local.js')
    if (m?.APP_VERSION) _version = m.APP_VERSION
  } catch {}
}

export const APP_VERSION = _version
